SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Players
WAITFOR DELAY '00:00:15'
SELECT * FROM Players
COMMIT TRAN
GO

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Players
WAITFOR DELAY '00:00:15'
SELECT * FROM Players
COMMIT TRAN