SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Participations
WAITFOR DELAY '00:00:05'
SELECT * FROM Participations
COMMIT TRAN
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Participations
WAITFOR DELAY '00:00:05'
SELECT * FROM Participations
COMMIT TRAN